"""create tables

Revision ID: 7a13fe95fd47
Revises: 
Create Date: 2019-01-08 22:14:03.728452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a13fe95fd47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('store_name', sa.String(
                        length=64), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=64), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=64), nullable=False),
                    sa.Column('email', sa.String(length=120), nullable=False),
                    sa.Column('password_hash', sa.String(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('company_logo', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('images',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('image_name', sa.Text(), nullable=False),
                    sa.Column('image_caption', sa.Text(), nullable=True),
                    sa.Column('image_url', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('marketplaces',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('marketplace_name', sa.String(
                        length=64), nullable=False),
                    sa.Column('shop_id', sa.Integer(), nullable=False),
                    sa.Column('shop_name', sa.String(
                        length=64), nullable=False),
                    sa.Column('access_token', sa.String(
                        length=64), nullable=False),
                    sa.Column('refresh_token', sa.String(
                        length=64), nullable=True),
                    sa.Column('shop_description', sa.Text(), nullable=True),
                    sa.Column('shop_logo', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('marketplaces')
    op.drop_table('images')
    op.drop_index(op.f('ix_users_store_name'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
